### ISSUE TITLE
Drop Julia 1.1, 1.2 from CI

### ISSUE THREAD

**Issue by mtanneau** [JuliaSmoothOptimizers/QPSReader.jl#13]
I think it would be enough to have
```yml
# .travis.yml
julia:
  - 1.0
  - 1
  - nightly
```
and
```yml
# .appveyor.yml
environment:
  matrix:
  - julia_version: 1.0
  - julia_version: 1
  - julia_version: nightly
```

since `1` should automatically point to the newest stable `1.Y.Z` release.
